name: Android CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assembleRelease -Pandroid.injected.build.abi=arm64-v8a
      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: app-release
          path: build/outputs/apk/release/*.apk
          archive: false
